.\" Manpage for gauthenticator.
.\" Contact megia_oscar@gmail.com to correct errors or typos.
.TH GAUTHENTICATOR 1 "Apr 2019" "version 0.2" "gauthenticator man page"
.SH NAME
gauthenticator \- Handle one time key authentication on desktop.
.SH SYNOPSIS
gauthenticator
.SH DESCRIPTION
gauthenticator is a GTK+ application for manage several accounts with two factor authentication codes TOTP (Time-Based One-Time Password Algorithm).
.SH OPTIONS
The gauthenticator does not take any options.
.SH SEE ALSO
google-authenticator(1) pam_google_authenticator(8)
.SH BUGS
No known bugs.
.SH AUTHOR
gauthenticator is a fork from google-authenticator-libpam <https://github.com/google/google-authenticator-libpam> by Oscar Megía López (megia.oscar@gmail.com)
.SH SEE ALSO
The gauthenticator source code and all documentation may be downloaded
from <https://github.com/Oscar65/gauthenticator>.
